[package]
name = "wasapi"
version = "0.9.0"
edition = "2018"
authors = ["HEnquist <henrik.enquist@gmail.com>"]
description = "Bindings for the Wasapi API on Windows"
license = "MIT"
repository = "https://github.com/HEnquist/wasapi-rs"
keywords = ["audio", "sound", "windows", "wasapi"]
categories = ["multimedia::audio", "os::windows-apis"]
readme = "README.md"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.windows]
version = "0.30.0"
features = ["Foundation",
            "Win32_Devices_Properties",
            "Win32_Foundation",
            "Win32_Media_Audio",
            "Win32_Media_Audio_Endpoints",
            "Win32_Media_KernelStreaming",
            "Win32_Media_Multimedia",
            "Win32_System_Com",
            "Win32_System_Com_StructuredStorage",
            "Win32_System_Threading",
            "Win32_System_ProcessStatus",
            "Win32_Security",
            "Win32_UI_Shell_PropertiesSystem",
            "Win32_UI_WindowsAndMessaging",
]

[dependencies]
widestring = "0.5.1"
log = "0.4.14"
windows_macros = "0.30.0"

[dev-dependencies]
simplelog = "0.11.2"

[package.metadata.docs.rs]
default-target = "x86_64-pc-windows-msvc"
targets = ["x86_64-pc-windows-msvc"]